### ISSUE TITLE
Raster zonal stats: nodata arg doesn't work

### ISSUE THREAD

**Issue by alronlam** [thinkingmachines/geowrangler#119]
Hi! I think the `nodata` arg doesn't work for raster zonal stats, as I still got NaNs even when specifying 0.

![nodata_issue](https://user-images.githubusercontent.com/1049495/183866414-2104291d-6e33-4276-98fc-df9c0a0ec48b.PNG)

**Comment by butchtm** [comment]
Hi @alron, just confirming --  the `nodata`  value is a metadata property of the tiff file which we need to get from the raster file itself. 
```
import rasterio as rio
with rio.open(f'{DATA_DIR}/ntl2016.tif') as src:
    indexes = src.indexes
    nodata = src.nodata
```
If you check the `nodata` value, its set to None.

Its the value that the raster file sets when it has no data for that pixel value -- I checked the ntlights raster files and it seems that there is no `nodata` value set, meaning that within the boundaries of the ntlights raster file, all pixels have valid values. 
Since `0.0` is a valid value for the range of radiance values (neg/pos),  if you set the `nodata` parameter to 0.0, then those pixels containing `0.` are then treated as `NaN`s.

What I did was since there was no way for the valid radiance values to be set to `-999`, I used that as the `nodata` parameter.
So you can try the following:
```
gdf_with_features  = rzs.create_raster_zonal_stats(
                                            gdf_with_features, 
                                            tl2016_file,
                                            aggregation=aggregation,
                                            extra_args=dict(band_num=1, nodata=-999)
                                   )
```
