### ISSUE TITLE
Geometry Simplification

### ISSUE THREAD

**Issue by tm-kah-alforja** [thinkingmachines/geowrangler#66]

**Comment by joshuacortez** [comment]
definition of simplification: 

> Simplify polygons just enough to meet size limitations of tools like BQ, Tableau etc while still retaining as much detail as possible
> 
> The goal is to simplify a very complex geometry “just enough” to hit some size limit.
> 
> Sometimes, tools like BQ, tableau, etc. have size/complexity limits when dealing with polygon geometries. This usually happens in the case of country polygons. In these cases, we want to simplify the polygon just enough to be within said limits, but not over-simplifying such that we unnecessarily lose too much detail. 
>

**Comment by joshuacortez** [comment]
I think we can close this issue you can use geopandas's [simplify](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.simplify.html) and setting a meter threshold instead of a file size threshold. A file size threshold is also tricky to compute exactly since it may change based on the hardware and the dependencies
